### ISSUE TITLE
Collaboration (not an issue)

### ISSUE THREAD

**Issue by fugalfunkster** [mvolk/ciderlib#8]
Howdy, I wrote a small cider app you starred recently. I'm interested in collaborating. Perhaps we could chat over a cider at Bushwackers on Powell sometime?

**Comment by mvolk** [comment]
For sure! I'm impressed with your work on [ciderData](https://github.com/fugalfunkster/ciderData), and I'm keen on including juice property profiles and blending tools in ciderlib/ciderref in future iterations. I'll reach out via email.
